version: '3'
services:
  web:
    build: ./Agence
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
      - mail
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/AgenceConnect

  db:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AgenceConnect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  mail:
    build: ./mail
    environment:
      - MAIL_HOST=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USER=user
      - MAIL_PASSWORD=password
  dns:
    build: ./dns
    ports:
      - "54:54/udp"
      - "54:54/tcp"

volumes:
  postgres_data: