# Utilisation de l'image PostgreSQL officielle
FROM postgres:latest

# Optionnel : Définir des variables d'environnement pour la configuration PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=AgenceConnect

# Copie de fichiers d'initialisation ou de configuration si nécessaire
# COPY init.sql /docker-entrypoint-initdb.d/