# Utilisation de l'image MailHog officielle
FROM mailhog/mailhog:latest

# Optionnel : Exposer le port SMTP de MailHog (par défaut : 1025) et le port HTTP (par défaut : 8025)
EXPOSE 1025 8025

# Commande par défaut pour démarrer MailHog
CMD ["MailHog"]